name: kamus_kamek
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  change_app_package_name: ^1.0.0
  cloud_firestore: ^2.4.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  flutter_launcher_icons: ^0.9.1
  flutter_spinkit: ^5.0.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.0.7
  google_ml_kit: ^0.6.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  shared_preferences: ^2.0.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Light.ttf
          weight: 300
        - asset: assets/font/Raleway-Regular.ttf
          weight: 400
        - asset: assets/font/Raleway-Medium.ttf
          weight: 500
        - asset: assets/font/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
