class CountryModel {
  String? code, country, flagUrl, hintText;

  CountryModel({this.code, this.flagUrl, this.country, this.hintText});
}

// final List<CountryModel> listCountries = [
//   CountryModel(country: "Afrikaans", code: "af", hintText: ""),
  
//   CountryModel(country: "Arabic", code: "ar", hintText: "أدخل النص"),
//   CountryModel(country: "Basque", code: "eu", hintText: "Idatzi testua"),
//   CountryModel(country: "Bengali", code: "bn", hintText: "লেখা অন্তর্ভুক্ত করুন"),
//   CountryModel(country: "Portuguese (Brazil)", code: "pt-BR", hintText: "Digite o texto"),
//   CountryModel(country: "Bulgarian", code: "bg", hintText: "Въведете текст"),
//   CountryModel(country: "Catalan", code: "ca", hintText: "Introduïu text"),
//   CountryModel(country: "Croatian", code: "hr", hintText: "Unesite tekst"),
//   CountryModel(country: "Czech", code: "cs", hintText: "Zadejte text"),
//   CountryModel(country: "Danish", code: "da", hintText: "Indtast tekst"),
//   CountryModel(country: "Dutch", code: "nl", hintText: "Tekst invoeren"),
//   CountryModel(country: "English (US)", code: "en", hintText: "Enter text"),
//   CountryModel(country: "Estonian", code: "et", hintText: "Sisestage tekst"),
//   CountryModel(country: "Filipino", code: "fil", hintText: "Ipasok ang teksto"),
//   CountryModel(country: "Finnish", code: "fi", hintText: "Kirjoita teksti"),
//   CountryModel(country: "French", code: "fr", hintText: "Entrez du texte"),
//   CountryModel(country: "German", code: "de", hintText: "Text eingeben"),
//   CountryModel(country: "Greek", code: "el", hintText: "Εισαγάγετε κείμενο"),
//   CountryModel(country: "Gujarati", code: "gu", hintText: "ટેક્સ્ટ દાખલ કરો"),
//   CountryModel(country: "Hebrew", code: "iw", hintText: "הזן טקסט"),
//   CountryModel(country: "Hindi", code: "hi", hintText: "लिखना प्रारम्भ करें"),
//   CountryModel(country: "Hungarian", code: "hu", hintText: "Írjon be szöveget"),
//   CountryModel(country: "Icelandic", code: "is", hintText: "Sláðu inn texta"),
//   CountryModel(country: "Indonesian", code: "id", hintText: "Masukkan teks"),
//   CountryModel(country: "Italian", code: "it", hintText: "Inserire il testo"),
//   CountryModel(country: "Japanese", code: "ja", hintText: "テキストを入力してください"),
//   CountryModel(country: "Kannada", code: "kn", hintText: "ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ"),
//   CountryModel(country: "Korean", code: "ko", hintText: "텍스트 입력"),
//   CountryModel(country: "Latvian", code: "lv", hintText: "Ievadiet tekstu"),
//   CountryModel(country: "Lithuanian", code: "lt", hintText: "Įveskite tekstą"),
//   CountryModel(country: "Malay", code: "ms", hintText: "Masukkan teks"),
//   CountryModel(country: "Malayalam", code: "ml", hintText: "വാചകം നൽകുക"),
//   CountryModel(country: "Marathi", code: "mr", hintText: "मजकूर प्रविष्ट करा"),
//   CountryModel(country: "Norwegian", code: "no", hintText: "Skriv inn tekst"),
//   CountryModel(country: "Polish", code: "pl", hintText: "Wprowadź tekst"),
//   CountryModel(country: "Portuguese (Portugal)", code: "pt-PT", hintText: "Digite o texto"),
//   CountryModel(country: "Romanian", code: "ro", hintText: "Introduceți text"),
//   CountryModel(country: "Russian", code: "ru", hintText: "Введите текст"),
//   CountryModel(country: "Serbian", code: "sr", hintText: "Унесите текст"),
//   CountryModel(country: "Chinese (Simplified)", code: "zh-CN", hintText: "输入文字"),
//   CountryModel(country: "Slovak", code: "sk", hintText: "Zadajte text"),
//   CountryModel(country: "Slovenian", code: "sl", hintText: "Vnesite besedilo"),
//   CountryModel(country: "Spanish", code: "es", hintText: "Ingrese texto"),
//   CountryModel(country: "Swahili", code: "sw", hintText: "Ingiza maandishi"),
//   CountryModel(country: "Swedish", code: "sv", hintText: "Skriv text"),
//   CountryModel(country: "Tamil", code: "ta", hintText: "உரையை உள்ளிடவும்"),
//   CountryModel(country: "Telugu", code: "te", hintText: "వచనాన్ని నమోదు చేయండి"),
//   CountryModel(country: "Thai", code: "th", hintText: "ป้อนข้อความ"),
//   CountryModel(country: "Chinese (Traditional)", code: "zh-TW", hintText: "輸入文字"),
//   CountryModel(country: "Turkish", code: "tr", hintText: "Metin girin"),
//   CountryModel(country: "Urdu", code: "ur", hintText: "متن درج کریں۔"),
//   CountryModel(country: "Ukrainian", code: "uk", hintText: "Введіть текст"),
//   CountryModel(country: "Vietnamese", code: "vi", hintText: "Nhập văn bản"),
//   CountryModel(country: "Welsh", code: "cy", hintText: "Rhowch destun"),
// ];
final List<CountryModel> listCountries = [
  CountryModel(country: "Amharic", code: "am", hintText: "ጽሑፍ ያስገቡ"),
  CountryModel(country: "Arabic", code: "ar", hintText: "أدخل النص"),
  CountryModel(country: "Basque", code: "eu", hintText: "Idatzi testua"),
  CountryModel(country: "Bengali", code: "bn", hintText: "লেখা অন্তর্ভুক্ত করুন"),
  CountryModel(country: "Portuguese (Brazil)", code: "pt-BR", hintText: "Digite o texto"),
  CountryModel(country: "Bulgarian", code: "bg", hintText: "Въведете текст"),
  CountryModel(country: "Catalan", code: "ca", hintText: "Introduïu text"),
  CountryModel(country: "Croatian", code: "hr", hintText: "Unesite tekst"),
  CountryModel(country: "Czech", code: "cs", hintText: "Zadejte text"),
  CountryModel(country: "Danish", code: "da", hintText: "Indtast tekst"),
  CountryModel(country: "Dutch", code: "nl", hintText: "Tekst invoeren"),
  CountryModel(country: "English (US)", code: "en", hintText: "Enter text"),
  CountryModel(country: "Estonian", code: "et", hintText: "Sisestage tekst"),
  CountryModel(country: "Filipino", code: "fil", hintText: "Ipasok ang teksto"),
  CountryModel(country: "Finnish", code: "fi", hintText: "Kirjoita teksti"),
  CountryModel(country: "French", code: "fr", hintText: "Entrez du texte"),
  CountryModel(country: "German", code: "de", hintText: "Text eingeben"),
  CountryModel(country: "Greek", code: "el", hintText: "Εισαγάγετε κείμενο"),
  CountryModel(country: "Gujarati", code: "gu", hintText: "ટેક્સ્ટ દાખલ કરો"),
  CountryModel(country: "Hebrew", code: "iw", hintText: "הזן טקסט"),
  CountryModel(country: "Hindi", code: "hi", hintText: "लिखना प्रारम्भ करें"),
  CountryModel(country: "Hungarian", code: "hu", hintText: "Írjon be szöveget"),
  CountryModel(country: "Icelandic", code: "is", hintText: "Sláðu inn texta"),
  CountryModel(country: "Indonesian", code: "id", hintText: "Masukkan teks"),
  CountryModel(country: "Italian", code: "it", hintText: "Inserire il testo"),
  CountryModel(country: "Japanese", code: "ja", hintText: "テキストを入力してください"),
  CountryModel(country: "Kannada", code: "kn", hintText: "ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ"),
  CountryModel(country: "Korean", code: "ko", hintText: "텍스트 입력"),
  CountryModel(country: "Latvian", code: "lv", hintText: "Ievadiet tekstu"),
  CountryModel(country: "Lithuanian", code: "lt", hintText: "Įveskite tekstą"),
  CountryModel(country: "Malay", code: "ms", hintText: "Masukkan teks"),
  CountryModel(country: "Malayalam", code: "ml", hintText: "വാചകം നൽകുക"),
  CountryModel(country: "Marathi", code: "mr", hintText: "मजकूर प्रविष्ट करा"),
  CountryModel(country: "Norwegian", code: "no", hintText: "Skriv inn tekst"),
  CountryModel(country: "Polish", code: "pl", hintText: "Wprowadź tekst"),
  CountryModel(country: "Portuguese (Portugal)", code: "pt-PT", hintText: "Digite o texto"),
  CountryModel(country: "Romanian", code: "ro", hintText: "Introduceți text"),
  CountryModel(country: "Russian", code: "ru", hintText: "Введите текст"),
  CountryModel(country: "Serbian", code: "sr", hintText: "Унесите текст"),
  CountryModel(country: "Chinese (Simplified)", code: "zh-CN", hintText: "输入文字"),
  CountryModel(country: "Slovak", code: "sk", hintText: "Zadajte text"),
  CountryModel(country: "Slovenian", code: "sl", hintText: "Vnesite besedilo"),
  CountryModel(country: "Spanish", code: "es", hintText: "Ingrese texto"),
  CountryModel(country: "Swahili", code: "sw", hintText: "Ingiza maandishi"),
  CountryModel(country: "Swedish", code: "sv", hintText: "Skriv text"),
  CountryModel(country: "Tamil", code: "ta", hintText: "உரையை உள்ளிடவும்"),
  CountryModel(country: "Telugu", code: "te", hintText: "వచనాన్ని నమోదు చేయండి"),
  CountryModel(country: "Thai", code: "th", hintText: "ป้อนข้อความ"),
  CountryModel(country: "Chinese (Traditional)", code: "zh-TW", hintText: "輸入文字"),
  CountryModel(country: "Turkish", code: "tr", hintText: "Metin girin"),
  CountryModel(country: "Urdu", code: "ur", hintText: "متن درج کریں۔"),
  CountryModel(country: "Ukrainian", code: "uk", hintText: "Введіть текст"),
  CountryModel(country: "Vietnamese", code: "vi", hintText: "Nhập văn bản"),
  CountryModel(country: "Welsh", code: "cy", hintText: "Rhowch destun"),
];
